# Generated by Django 3.0.8 on 2020-09-26 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
